basePath: /
definitions:
  project_category-api_model.CategoryInput:
    properties:
      category:
        example: Makanan
        type: string
    required:
    - category
    type: object
  project_category-api_model.Response:
    properties:
      responseCode:
        type: integer
      responseData: {}
      responseDesc:
        type: string
      responseMeta:
        $ref: '#/definitions/project_category-api_model.ResponseMeta'
    type: object
  project_category-api_model.ResponseMeta:
    properties:
      page:
        type: integer
      per_page:
        type: integer
      total_pages:
        type: integer
      total_records:
        type: integer
    type: object
  project_product-api_model.ProductInput:
    properties:
      id_category:
        example: 1
        type: integer
      product:
        example: Chitato
        type: string
    required:
    - id_category
    - product
    type: object
  project_product-api_model.Response:
    properties:
      responseCode:
        type: integer
      responseData: {}
      responseDesc:
        type: string
      responseMeta:
        $ref: '#/definitions/project_product-api_model.ResponseMeta'
    type: object
  project_product-api_model.ResponseMeta:
    properties:
      page:
        type: integer
      per_page:
        type: integer
      total_pages:
        type: integer
      total_records:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for managing Point of Sale.
  title: Point of Sale API
  version: "1.0"
paths:
  /categories:
    get:
      consumes:
      - application/json
      description: Get all categories
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/project_category-api_model.Response'
      summary: Get all categories
      tags:
      - categories
    post:
      consumes:
      - application/json
      description: Create a new category
      parameters:
      - description: Category
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/project_category-api_model.CategoryInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/project_category-api_model.Response'
      summary: Create a new category
      tags:
      - categories
  /categories/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a category
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/project_category-api_model.Response'
      summary: Delete a category
      tags:
      - categories
    get:
      consumes:
      - application/json
      description: Get category by ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/project_category-api_model.Response'
      summary: Get category by ID
      tags:
      - categories
    put:
      consumes:
      - application/json
      description: Update a category
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      - description: Category
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/project_category-api_model.CategoryInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/project_category-api_model.Response'
      summary: Update a category
      tags:
      - categories
  /categories/permanently/{id}:
    delete:
      consumes:
      - application/json
      description: Permanently delete a category
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/project_category-api_model.Response'
      summary: Permanently delete a category
      tags:
      - categories
  /categories/with-deleted:
    get:
      consumes:
      - application/json
      description: Get all categories including deleted
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/project_category-api_model.Response'
      summary: Get all categories including deleted
      tags:
      - categories
  /products:
    get:
      consumes:
      - application/json
      description: Get all products
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/project_product-api_model.Response'
      summary: Get all products
      tags:
      - products
    post:
      consumes:
      - application/json
      description: Create a new product
      parameters:
      - description: Product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/project_product-api_model.ProductInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/project_product-api_model.Response'
      summary: Create a new product
      tags:
      - products
  /products/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a product
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/project_product-api_model.Response'
      summary: Delete a product
      tags:
      - products
    get:
      consumes:
      - application/json
      description: Get product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/project_product-api_model.Response'
      summary: Get product by ID
      tags:
      - products
    put:
      consumes:
      - application/json
      description: Update a product
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: Product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/project_product-api_model.ProductInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/project_product-api_model.Response'
      summary: Update a product
      tags:
      - products
  /products/category/{id_category}:
    get:
      consumes:
      - application/json
      description: Get products by category ID
      parameters:
      - description: Category ID
        in: path
        name: id_category
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/project_product-api_model.Response'
      summary: Get products by category ID
      tags:
      - products
  /products/permanently/{id}:
    delete:
      consumes:
      - application/json
      description: Permanently delete a product
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/project_product-api_model.Response'
      summary: Permanently delete a product
      tags:
      - products
  /products/with-deleted:
    get:
      consumes:
      - application/json
      description: Get all products including deleted
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/project_product-api_model.Response'
      summary: Get all products including deleted
      tags:
      - products
swagger: "2.0"
